site_name: Flameshot Developer Docs
site_url: https://flameshot.org/docs/dev/
repo_url: https://github.com/flameshot-org/flameshot/
edit_uri: tree/master/docs/dev/
docs_dir: dev
site_dir: dev-docs-output
markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: "#"
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - mkdoxy:
      projects:
        flameshot:
          src-dirs: ../src/
          full-doc: True
          doxy-cfg:
            FILE_PATTERNS: "*.cpp *.h"
            EXCLUDE_PATTERNS: "*/capturetool.h"
            FULL_PATH_NAMES: "NO"
            SHOW_USED_FILES: "NO"
            RECURSIVE: True
            CLASS_DIAGRAMS: "YES"
            CLASS_GRAPH: "YES"
            DOT_TRANSPARENT: "YES"
            HAVE_DOT: "YES"

      save-api: mkdoxy-generated
      debug: False
      ignore-errors: False
  - mike:
      canonical_version: "latest"

theme:
  name: material
  logo: https://flameshot.org/flameshot-icon.svg

extra:
  version:
    provider: mike

nav:
  - Overview: index.md
  - Debugging: debugging.md
  - FAQ: faq.md
  - 'Maintaining the documentation': docs.md
  - API:
      - Classes: flameshot/classes.md
      - 'Class Hierarchy': flameshot/hierarchy.md
      - Files: flameshot/files.md
